# Generated by Django 5.1.3 on 2024-12-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('price', models.FloatField()),
                ('pdetails', models.CharField(max_length=200, verbose_name='Product details')),
                ('cat', models.IntegerField(choices=[(1, 'Cake'), (2, 'Chocolates'), (3, 'flowerpot')], verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Availbale')),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
