# Generated by Django 5.1.3 on 2024-12-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftbox_app', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Cake'), (2, 'Chocolates'), (3, 'flowerpot'), (4, 'Personlisedgift'), (5, 'Plants')], verbose_name='Category'),
        ),
    ]
