# Generated by Django 5.1.3 on 2024-12-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftbox_app', '0003_alter_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Cake'), (2, 'Chocolates'), (3, 'flowerpot'), (4, 'Personlisedgift'), (5, 'Plants'), (6, 'Perfumes'), (7, 'Combos')], verbose_name='Category'),
        ),
    ]
